---
# tasks file for RedHat

- name: Ensure InfluxDB repo file exists.
  template:
    src: influxdb.repo.j2
    dest: /etc/yum.repos.d/influxdb.repo
    owner: root
    group: root
    mode: 0644
  when: influxdb_repo

- name: Ensure InfluxDB packages are installed (RedHat).
  yum:
    name: '{{ item }}'
    state: present
  with_items: '{{ influxdb_packages }}'
